profiles:
  sarka:
    sharepoint_root: "C:/Users/REPLACE_ME/University of Edinburgh"

paths:
  inventory_db:
    rel_db: "Carbon accounting of fire events - Fire-Emissions-Databases/inventory_db/database/pooled_inventory.sqlite"
   
  showroom:  
    rel_raw: "Carbon accounting of fire events - Fire-Emissions-Databases/inventory_db/raw/showrooms"
  survey:  
    rel_raw: "Carbon accounting of fire events - Fire-Emissions-Databases/inventory_db/raw/surveys"
  insurance:  
    rel_raw: "Carbon accounting of fire events - Fire-Emissions-Databases/inventory_db/raw/insurance"
